### PR TITLE
Add `BindCommand` Support for Typed Bindings Extensions

### LINKED ISSUE #181: [Proposal] Further enhance typed binding support by adding BindCommand
### Feature name

Further enhance typed binding support by adding `BindCommand`

### Link to discussion

n/a

### Progress tracker

- [x] Android Implementation
- [x] iOS Implementation
- [x] MacCatalyst Implementation
- [x] Windows Implementation
- [x] Tizen Implementation
- [x] Unit Tests
- [x] Samples
- [x] Documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/226/files

### Summary

The work carried out in #155 didn't bring full typed binding support up to par with the existing binding support. We want to add in the `BindCommand` implementation to match the old binding functionality.

### Motivation

Quicker bindings means quicker apps.

### Detailed Design

```csharp
public static TBindable BindCommand<TBindable, TBindingContext, TSource>(
    this TBindable bindable,
    Func<TBindingContext, TSource> getter,
    TSource? source = null,
    string? parameterPath = Binding.SelfPath,
    object? parameterSource = null) where TBindable : BindableObject
{
    ...
}
```

### Usage Syntax

```markdown
new Button().BindCommand(static (ViewModel vm) => vm.SubmitCommand);
```

### Drawbacks

_No response_

### Alternatives

_No response_

### Unresolved Questions

_No response_

### PR DESCRIPTION
**Pull request by brminnick**
### Description of Change ###

This PR adds the following APIs which enables users to use `.BindCommand()` with Typed Bindings extensions:

```cs
/// <summary>Bind to the <typeparamref name="TBindable"/>'s default Command properties </summary>
public static TBindable BindCommand<TBindable, TCommandBindingContext>(
		this TBindable bindable,
		Expression<Func<TCommandBindingContext, ICommand>> getter,
		Action<TCommandBindingContext, ICommand>? setter = null,
		BindingMode mode = BindingMode.Default,
		TCommandBindingContext? source = default) where TBindable : BindableObject;

/// <summary>Bind to the <typeparamref name="TBindable"/>'s default Command properties </summary>
public static TBindable BindCommand<TBindable, TCommandBindingContext>(
		this TBindable bindable,
		Func<TCommandBindingContext, ICommand> getter,
		(Func<TCommandBindingContext, object?>, string)[] handlers,
		Action<TCommandBindingContext, ICommand>? setter = null,
		BindingMode mode = BindingMode.Default,
		TCommandBindingContext? source = default) where TBindable : BindableObject;

/// <summary>Bind to the <typeparamref name="TBindable"/>'s default Command and CommandParameter properties </summary>
public static TBindable BindCommand<TBindable, TCommandBindingContext, TParameterBindingContext, TParameterSource>(
		this TBindable bindable,
		Expression<Func<TCommandBindingContext, ICommand>> getter,
		Action<TCommandBindingContext, ICommand>? setter = null,
		TCommandBindingContext? source = default,
		BindingMode commandBindingMode = BindingMode.Default,
		Expression<Func<TParameterBindingContext, TParameterSource>>? parameterGetter = null,
		Action<TParameterBindingContext, TParameterSource>? parameterSetter = null,
		BindingMode parameterBindingMode = BindingMode.Default,
		TParameterBindingContext? parameterSource = default) where TBindable : BindableObject;

	/// <summary>Bind to the <typeparamref name="TBindable"/>'s default Command and CommandParameter properties </summary>
public static TBindable BindCommand<TBindable, TCommandBindingContext, TParameterBindingContext, TParameterSource>(
		this TBindable bindable,
		Func<TCommandBindingContext, ICommand> getter,
		(Func<TCommandBindingContext, object?>, string)[] handlers,
		Action<TCommandBindingContext, ICommand>? setter = null,
		TCommandBindingContext? source = default,
		BindingMode commandBindingMode = BindingMode.Default,
		Func<TParameterBindingContext, TParameterSource>? parameterGetter = null,
		(Func<TParameterBindingContext, object?>, string)[]? parameterHandlers = null,
		Action<TParameterBindingContext, TParameterSource>? parameterSetter = null,
		TParameterBindingContext? parameterSource = default,
		BindingMode parameterBindingMode = BindingMode.Default) where TBindable : BindableObject;
```

 ### Linked Issues ###

 - Fixes #181 

 ### PR Checklist ###
 
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [x] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui.Markup/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: 

 ### Additional information ###

This PR allows Typed Bindings to be used with `.BindCommand()`

```cs
new Button().BindCommand(static (ViewModel vm) => vm.Command, mode: BindingMode.OneTime);
```

Because `TypedBindingExtensions.cs` was growing in size (300+ LOC) and becoming difficult to manage, I created `TypedBindingExtensions.Handlers.cs` that contains all of the Typed Binding extension methods that require a handler parameter for nested bindings (e.g. `(Func<TCommandBindingContext, object?>, string)[] handlers`)

### CODE REVIEW

**Comment by brminnick** [comment]
@bijington Are you able to help with the updating the docs for this PR too?

**Review by pictos — COMMENTED** [review]
Can we show case it on our sample app?

**Comment by brminnick** [comment]
> Can we show case it on our sample app?

Of course! Updated ✅

**Comment by bijington** [comment]
> @bijington Are you able to help with the updating the docs for this PR too?

I cheated and added it to this PR https://github.com/MicrosoftDocs/CommunityToolkit/pull/226 to save on conflicts

**Review by bijington — DISMISSED** [review]
LGTM!

**Comment by brminnick** [comment]
Blocked until `Microsoft.CodeAnalysis.CSharp v4.5.0.0` is released:  https://github.com/dotnet/sdk/issues/30742

**Pull request merged**
