### PR TITLE
Do not generate TextAlignment extension if it's already generated by base type

### LINKED ISSUE #182: [BUG] TextAlignment Extension Throwing Compiler Error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if I extend the base Label class and  implement the ILabel interface, 

```
public class MyLabel : Label, ILabel
{

}
```

if I try to use the extended MyLabel class, text alignment extension will throw this exception

```
public MainPage()
{
	Content = new MyLabel
	{

	}.Center().TextCenter();
}
```

```
[CS0121](classifiedtextelementview-invokeaction:0): The call is ambiguous between the following methods or properties:
 'TextAlignmentExtensions_MyLabel.TextCenter<TAssignable>(TAssignable)' and 
'TextAlignmentExtensions_Label.TextCenter<TAssignable>(TAssignable)'
```

### Expected Behavior

No compiler Error

### Steps To Reproduce

See above

### Link to public reproduction project repository

https://github.com/danielftz/BugExample.MCTMarkupTextAlignment

### Environment

```markdown
- .NET MAUI C# Markup CommunityToolkit:
- OS: MacOS
- .NET MAUI: Latest CUrrent
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Youssef1313**
~~**Another suggested fix:** #206~~

~~(**ONLY ONE** of the PRs need to be merged)~~

 ### Description of Change ###

 

 ### Linked Issues ###
 

 - Fixes #182

 ### PR Checklist ###
 
 - [ ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [ ] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [ ] Rebased on top of `main` at time of PR
 - [ ] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui.Markup/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [ ] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pulls/XYZ 

 ### Additional information ###

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
```csharp
new Derived().M();

public class Base
{
}

public class Derived
{
}

public static class Extensions1
{
    public static void M<T>(this T b) where T : Base { }
}

public static class Extensions2
{
    public static void M<T>(this T b) where T : Derived { }
}
```

~~This sample code **does** compile and the compiler doesn't complain about ambiguity. I think I need to better understand why there was ambiguity in the first place.~~

**Edit:** IGNORE THIS COMMENT. I forgot to make `Derived` actually inherit `Base` 😄

**Comment by pictos** [comment]
We did the non-generic way before. I believe @brminnick added it. Brandon, can you give the context around that change? (if you was there)

**Comment by pictos** [comment]
@Youssef1313 here's some context around the usage of generics
https://github.com/CommunityToolkit/Maui.Markup/pull/150

**Comment by Youssef1313** [comment]
Ok, I think we can go with this approach.

**Review by brminnick — APPROVED** [review]
Thanks @Youssef1313!!

Apologies for not merging this sooner 🙌

**Pull request merged**
