### PR TITLE
Add `GesturesExtensions.TypedBindings.cs`

### LINKED ISSUE #191: [Proposal] Add TypedBindings to GesturesExtensions
### Feature name

Add TypedBindings to `GesturesExtensions`

### Progress tracker

- [x] Android Implementation
- [x] iOS Implementation
- [x] MacCatalyst Implementation
- [x] Windows Implementation
- [x] Tizen Implementation
- [x] Unit Tests
- [x] Samples
- [x] Documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/272

### Summary

This proposal augments GesturesExtensions by adding the following APIs that support Typed Bindings
- `.BindClickGesture()`
- `.BindSwipeGesture()`
- `.BindTapGesture()`

### Motivation

This is a continuation of #155 adding the ability to use Typed Bindings in `CommunityToolkit.Maui.Markup`

### Detailed Design

```cs
public static TGestureElement BindClickGesture<TGestureElement, TCommandBindingContext, TParameterBindingContext,
  TParameterSource>(
  this TGestureElement gestureElement,
  Expression<Func<TCommandBindingContext, ICommand>> getter,
  Action<TCommandBindingContext, ICommand>? setter = null,
  TCommandBindingContext? source = default,
  BindingMode commandBindingMode = BindingMode.Default,
  Expression<Func<TParameterBindingContext, TParameterSource>>? parameterGetter = null,
  Action<TParameterBindingContext, TParameterSource>? parameterSetter = null,
  BindingMode parameterBindingMode = BindingMode.Default,
  TParameterBindingContext? parameterSource = default,
  int? numberOfClicksRequired = null) where TGestureElement : BindableObject, IGestureRecognizers;

public static TGestureElement BindClickGesture<TGestureElement, TCommandBindingContext, TParameterBindingContext,
  TParameterSource>(
  this TGestureElement gestureElement,
  Func<TCommandBindingContext, ICommand>> getter,
  (Func<TCommandBindingContext, object?>, string)[] handlers,
  Action<TCommandBindingContext, ICommand>? setter = null,
  TCommandBindingContext? source = default,
  BindingMode commandBindingMode = BindingMode.Default,
  Expression<Func<TParameterBindingContext, TParameterSource>>? parameterGetter = null,
  Action<TParameterBindingContext, TParameterSource>? parameterSetter = null,
  BindingMode parameterBindingMode = BindingMode.Default,
  TParameterBindingContext? parameterSource = default,
  int? numberOfClicksRequired = null) where TGestureElement : BindableObject, IGestureRecognizers;

public static TGestureElement BindSwipeGesture<TGestureElement, TCommandBindingContext, TParameterBindingContext,
  TParameterSource>(
  this TGestureElement gestureElement,
  Expression<Func<TCommandBindingContext, ICommand>> getter,
  Action<TCommandBindingContext, ICommand>? setter = null,
  TCommandBindingContext? source = default,
  BindingMode commandBindingMode = BindingMode.Default,
  Expression<Func<TParameterBindingContext, TParameterSource>>? parameterGetter = null,
  Action<TParameterBindingContext, TParameterSource>? parameterSetter = null,
  BindingMode parameterBindingMode = BindingMode.Default,
  TParameterBindingContext? parameterSource = default,
  int? numberOfClicksRequired = null) where TGestureElement : BindableObject, IGestureRecognizers;

public static TGestureElement BindSwipeGesture<TGestureElement, TCommandBindingContext, TParameterBindingContext,
  TParameterSource>(
  this TGestureElement gestureElement,
  Func<TCommandBindingContext, ICommand>> getter,
  (Func<TCommandBindingContext, object?>, string)[] handlers,
  Action<TCommandBindingContext, ICommand>? setter = null,
  TCommandBindingContext? source = default,
  BindingMode commandBindingMode = BindingMode.Default,
  Expression<Func<TParameterBindingContext, TParameterSource>>? parameterGetter = null,
  Action<TParameterBindingContext, TParameterSource>? parameterSetter = null,
  BindingMode parameterBindingMode = BindingMode.Default,
  TParameterBindingContext? parameterSource = default,
  int? numberOfClicksRequired = null) where TGestureElement : BindableObject, IGestureRecognizers;

public static TGestureElement BindTapGesture<TGestureElement, TCommandBindingContext, TParameterBindingContext,
  TParameterSource>(
  this TGestureElement gestureElement,
  Expression<Func<TCommandBindingContext, ICommand>> getter,
  Action<TCommandBindingContext, ICommand>? setter = null,
  TCommandBindingContext? source = default,
  BindingMode commandBindingMode = BindingMode.Default,
  Expression<Func<TParameterBindingContext, TParameterSource>>? parameterGetter = null,
  Action<TParameterBindingContext, TParameterSource>? parameterSetter = null,
  BindingMode parameterBindingMode = BindingMode.Default,
  TParameterBindingContext? parameterSource = default,
  int? numberOfClicksRequired = null) where TGestureElement : BindableObject, IGestureRecognizers;

public static TGestureElement BindTapGesture<TGestureElement, TCommandBindingContext, TParameterBindingContext,
  TParameterSource>(
  this TGestureElement gestureElement,
  Func<TCommandBindingContext, ICommand>> getter,
  (Func<TCommandBindingContext, object?>, string)[] handlers,
  Action<TCommandBindingContext, ICommand>? setter = null,
  TCommandBindingContext? source = default,
  BindingMode commandBindingMode = BindingMode.Default,
  Expression<Func<TParameterBindingContext, TParameterSource>>? parameterGetter = null,
  Action<TParameterBindingContext, TParameterSource>? parameterSetter = null,
  BindingMode parameterBindingMode = BindingMode.Default,
  TParameterBindingContext? parameterSource = default,
  int? numberOfClicksRequired = null) where TGestureElement : BindableObject, IGestureRecognizers;
```

### Usage Syntax

```cs
new Label().BindTapGesture(static (ViewModel vm) => vm.TapGestureCommand, mode: BindingMode.OneWay)
```

### Drawbacks

None

### Alternatives

The following APIs currently exist without support for Typed Bindings (require reflection):
- BindClickGesture
- BindSwipeGesture
- BindTapGesture

### Unresolved Questions

None

### PR DESCRIPTION
**Pull request by brminnick**
### Description of Change ###

This PR implements Typed Bindings for GestureRecognizers

 ### Linked Issues ###

 - Fixes #191 

 ### PR Checklist ###
 - [x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
 - [x] Has tests (if omitted, state reason in description)
 - [ ] Has samples (if omitted, state reason in description)
 - [x] Rebased on top of `main` at time of PR
 - [x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui.Markup/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
 - [x] Documentation created or updated: https://github.com/MicrosoftDocs/CommunityToolkit/pull/272

### CODE REVIEW

**Comment by brminnick** [comment]
Thanks Shaun! We currently don't use GestureRecognizers in the sample app, but I'll find a way to squeeze it in 👍 

Yup! We do need a docs update. Any chance you're available to help? The Unit Tests added in this PR should demonstrate usage of the new APIs so that you don't have to wait on me to update the Sample App.

**Comment by bijington** [comment]
> Thanks Shaun! We currently don't use GestureRecognizers in the sample app, but I'll find a way to squeeze it in 👍
> 
> Yup! We do need a docs update. Any chance you're available to help? The Unit Tests added in this PR should demonstrate usage of the new APIs so that you don't have to wait on me to update the Sample App.

Yep I can take a look at the docs

**Comment by brminnick** [comment]
Hey @bijington! Any chance you've got the docs PR opened? 

I'd be great to merge this and publish a new release this week!

**Comment by bijington** [comment]
> Hey @bijington! Any chance you've got the docs PR opened? 
> 
> 
> 
> I'd be great to merge this and publish a new release this week!

Sorry it completely slipped my mind. I'm heading away for 2 weeks from tomorrow too so I won't be able to get it done before I return.

**Pull request merged**
